import { ArrowLeft, ArrowRight, Calendar, Clock, Share2 } from 'lucide-react';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { unstable_setRequestLocale } from 'next-intl/server';

import { badgeVariants } from '@/components/ui/badgeVariants';
import { buttonVariants } from '@/components/ui/buttonVariants';
import { Section } from '@/features/landing/Section';
import { LandingFooter } from '@/templates/LandingFooter';
import { LandingNavbar } from '@/templates/LandingNavbar';

// Blog posts data - in production, this would come from a CMS or MDX files
const blogPosts: Record<string, {
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readTime: string;
  content: string;
}> = {
  'why-chatgpt-cant-see-your-javascript-site': {
    title: 'Why ChatGPT Can\'t See Your JavaScript Site',
    excerpt: '98.9% of websites use JavaScript, but only 31% of AI crawlers can render it. Here\'s why your React, Vue, or Angular site is invisible to ChatGPT and what you can do about it.',
    category: 'Technical',
    date: '2026-01-10',
    readTime: '8 min read',
    content: `
## The JavaScript Rendering Problem

When you build a modern web application with React, Vue, Angular, or any other JavaScript framework, your HTML looks something like this when it first loads:

\`\`\`html
<!DOCTYPE html>
<html>
<head>
  <title>My App</title>
</head>
<body>
  <div id="root"></div>
  <script src="/bundle.js"></script>
</body>
</html>
\`\`\`

That's it. Just an empty div and a script tag. All your actual content—your product descriptions, blog posts, pricing information—is generated by JavaScript after the page loads.

For human users with modern browsers, this works perfectly. The JavaScript executes, React hydrates the page, and within milliseconds, your beautiful UI appears.

**But AI crawlers don't work like browsers.**

## How AI Crawlers Work

When ChatGPT's GPTBot, Perplexity's crawler, or other AI search engines visit your site, they typically:

1. **Make an HTTP request** to your URL
2. **Receive the raw HTML** response
3. **Parse the content** for indexing

Notice what's missing? **JavaScript execution.**

Most AI crawlers are simple HTTP clients. They don't run a full browser engine. They don't execute JavaScript. They don't wait for React to render your components.

They see that empty div. And that's what they index.

## The Numbers Are Stark

According to our research:

- **98.9%** of modern websites use JavaScript
- **Only 31%** of AI crawlers support JavaScript rendering
- **GPTBot** (ChatGPT) has limited JS support
- **PerplexityBot** has no JS rendering capability
- **ClaudeBot** (Anthropic) has limited support

This means if your site is built with a JavaScript framework and you haven't implemented server-side rendering or pre-rendering, you're invisible to most AI search engines.

## Why This Matters Now

AI search is growing at **400% year-over-year**. ChatGPT Search launched in November 2024 and now has access to 200M+ users. Perplexity is becoming a go-to research tool for millions.

When users ask these AI assistants about products in your category, they cite sources. If your site is invisible, you won't be cited. Your competitors will.

## The Solutions

There are several ways to make your JavaScript site visible to AI crawlers:

### 1. Server-Side Rendering (SSR)

Frameworks like Next.js, Nuxt, and SvelteKit can render your pages on the server, sending fully-formed HTML to crawlers.

**Pros:** Native solution, good performance
**Cons:** Requires rebuilding your app, complex migration

### 2. Static Site Generation (SSG)

Pre-render all your pages at build time.

**Pros:** Fast, simple
**Cons:** Doesn't work for dynamic content, long build times for large sites

### 3. Dynamic Rendering / Pre-rendering

Detect AI crawlers and serve them pre-rendered HTML while serving regular JavaScript to browsers.

**Pros:** No code changes to your app, works with any framework
**Cons:** Requires infrastructure setup

### 4. CrawlReady (What We Built)

CrawlReady implements dynamic rendering as a service. We detect AI crawlers, render your JavaScript pages in under 200ms, and serve the fully-rendered HTML.

- **5-minute setup** - Simple middleware integration
- **No code changes** - Works with your existing app
- **Sub-200ms rendering** - Fast enough for crawler timeouts
- **AI-optimized schema** - Automatically inject structured data

## Check Your Site

Want to know if AI crawlers can see your site? Use our [free AI Crawler Checker](/crawler-checker) to get an instant compatibility report.

## Conclusion

The shift to AI search is happening now. Early movers who optimize for AI visibility will establish authority in their categories. Don't wait until your competitors dominate AI search results.

[Join CrawlReady's early access](/#early-access) and get 50% off forever.
    `,
  },
  'how-we-built-the-ai-crawler-checker': {
    title: 'How We Built the AI Crawler Checker',
    excerpt: 'A deep dive into the technical architecture behind our free AI crawler compatibility tool. Learn how we simulate different AI crawlers and analyze JavaScript rendering.',
    category: 'Engineering',
    date: '2026-01-08',
    readTime: '12 min read',
    content: `
## Introduction

When we launched CrawlReady, we knew we needed a way to demonstrate the JavaScript rendering problem to potential users. That's why we built the [AI Crawler Checker](/crawler-checker)—a free tool that analyzes any website's compatibility with major AI crawlers.

In this post, I'll share the technical architecture behind the tool and some of the interesting challenges we solved.

## The Core Problem

To accurately assess AI crawler compatibility, we need to answer several questions:

1. **Does the site rely on JavaScript for content?**
2. **What content is visible without JavaScript execution?**
3. **What structured data (Schema.org) is present?**
4. **Are there any crawler-blocking mechanisms?**

Each of these requires different analysis techniques.

## Architecture Overview

The crawler checker consists of three main components:

1. **Dual-fetch system** - Fetches pages with and without JavaScript
2. **Content analyzer** - Compares rendered vs. raw HTML
3. **Schema parser** - Extracts and validates structured data

### Dual-Fetch System

We make two requests to each URL:

\`\`\`typescript
// Simple HTTP fetch (what most AI crawlers do)
const rawResponse = await fetch(url, {
  headers: {
    'User-Agent': 'PerplexityBot/1.0'
  }
});
const rawHtml = await rawResponse.text();

// Headless browser fetch (full JavaScript execution)
const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto(url, { waitUntil: 'networkidle0' });
const renderedHtml = await page.content();
\`\`\`

By comparing these two responses, we can determine how much content depends on JavaScript.

### Content Analysis

We extract text content from both versions and calculate a "content delta":

\`\`\`typescript
const rawText = extractTextContent(rawHtml);
const renderedText = extractTextContent(renderedHtml);

const contentDelta = {
  rawWordCount: rawText.split(/\\s+/).length,
  renderedWordCount: renderedText.split(/\\s+/).length,
  percentageIncrease: calculateIncrease(rawText, renderedText)
};
\`\`\`

If the rendered version has significantly more content, the site relies heavily on JavaScript.

### Schema.org Analysis

We parse both JSON-LD and microdata formats:

\`\`\`typescript
// JSON-LD extraction
const jsonLdScripts = document.querySelectorAll(
  'script[type="application/ld+json"]'
);

// Microdata extraction
const microdataItems = document.querySelectorAll('[itemscope]');
\`\`\`

We then validate the schemas against Schema.org specifications and check for AI-friendly properties.

## Crawler Simulation

Different AI crawlers have different capabilities. We simulate each one:

| Crawler | JavaScript Support | Timeout | User Agent |
|---------|-------------------|---------|------------|
| GPTBot | Limited | 5s | GPTBot/1.0 |
| PerplexityBot | None | 3s | PerplexityBot |
| ClaudeBot | Limited | 5s | ClaudeBot/1.0 |
| GoogleBot | Full | 10s | Googlebot/2.1 |

For each crawler, we adjust our simulation parameters accordingly.

## Scoring Algorithm

We calculate a 0-100 compatibility score based on:

- **Content accessibility** (40%) - How much content is visible without JS
- **Schema markup** (25%) - Quality and completeness of structured data
- **Technical factors** (20%) - robots.txt, meta tags, response times
- **Security headers** (15%) - HTTPS, CSP, etc.

\`\`\`typescript
const score = 
  contentScore * 0.4 +
  schemaScore * 0.25 +
  technicalScore * 0.2 +
  securityScore * 0.15;
\`\`\`

## Performance Optimizations

Running headless browsers is expensive. We implemented several optimizations:

1. **Request queuing** - BullMQ manages concurrent browser instances
2. **Caching** - Results cached in Redis for 24 hours
3. **Resource blocking** - Skip images, fonts, and tracking scripts
4. **Timeout management** - Aggressive timeouts prevent hanging

## Try It Yourself

The [AI Crawler Checker](/crawler-checker) is completely free and requires no signup. Enter any URL and get an instant compatibility report.

If you're building something similar, I'm happy to chat about the technical details. Find me on Twitter [@medartus](https://twitter.com/medartus).

## What's Next

We're working on several improvements:

- Historical tracking (see how your score changes over time)
- Competitive analysis (compare against competitors)
- Automated recommendations (specific code fixes)

[Join early access](/#early-access) to be the first to try these features.
    `,
  },
};

export async function generateMetadata(props: { params: { locale: string; slug: string } }) {
  const post = blogPosts[props.params.slug];

  if (!post) {
    return {
      title: 'Post Not Found - CrawlReady Blog',
    };
  }

  return {
    title: `${post.title} - CrawlReady Blog`,
    description: post.excerpt,
  };
}

export function generateStaticParams() {
  return Object.keys(blogPosts).map(slug => ({ slug }));
}

const BlogPostPage = (props: { params: { locale: string; slug: string } }) => {
  unstable_setRequestLocale(props.params.locale);

  const post = blogPosts[props.params.slug];

  if (!post) {
    notFound();
  }

  // Simple markdown-like rendering (in production, use a proper MDX processor)
  const renderContent = (content: string) => {
    return content
      .split('\n\n')
      .map((block, index) => {
        // Headers
        if (block.startsWith('## ')) {
          return (
            <h2 key={index} className="mb-4 mt-8 text-2xl font-bold text-gray-900 dark:text-white">
              {block.replace('## ', '')}
            </h2>
          );
        }
        if (block.startsWith('### ')) {
          return (
            <h3 key={index} className="mb-3 mt-6 text-xl font-semibold text-gray-900 dark:text-white">
              {block.replace('### ', '')}
            </h3>
          );
        }

        // Code blocks
        if (block.startsWith('```')) {
          const lines = block.split('\n');
          const code = lines.slice(1, -1).join('\n');
          return (
            <pre key={index} className="my-4 overflow-x-auto rounded-lg bg-gray-900 p-4 text-sm text-gray-100">
              <code>{code}</code>
            </pre>
          );
        }

        // Tables (simple implementation)
        if (block.includes('|') && block.includes('---')) {
          const rows = block.split('\n').filter(row => row.trim() && !row.includes('---'));
          return (
            <div key={index} className="my-4 overflow-x-auto">
              <table className="w-full border-collapse text-sm">
                <thead>
                  <tr className="border-b border-gray-200 dark:border-gray-700">
                    {rows[0]?.split('|').filter(Boolean).map((cell, i) => (
                      <th key={i} className="px-4 py-2 text-left font-semibold text-gray-900 dark:text-white">
                        {cell.trim()}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {rows.slice(1).map((row, rowIndex) => (
                    <tr key={rowIndex} className="border-b border-gray-100 dark:border-gray-800">
                      {row.split('|').filter(Boolean).map((cell, cellIndex) => (
                        <td key={cellIndex} className="px-4 py-2 text-gray-600 dark:text-gray-400">
                          {cell.trim()}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          );
        }

        // Lists
        if (block.match(/^[-*]\s/m)) {
          const items = block.split('\n').filter(line => line.match(/^[-*]\s/));
          return (
            <ul key={index} className="my-4 list-disc space-y-2 pl-6 text-gray-600 dark:text-gray-300">
              {items.map((item, i) => (
                <li key={i}>{item.replace(/^[-*]\s/, '')}</li>
              ))}
            </ul>
          );
        }

        if (block.match(/^\d+\.\s/m)) {
          const items = block.split('\n').filter(line => line.match(/^\d+\.\s/));
          return (
            <ol key={index} className="my-4 list-decimal space-y-2 pl-6 text-gray-600 dark:text-gray-300">
              {items.map((item, i) => (
                <li key={i}>{item.replace(/^\d+\.\s/, '')}</li>
              ))}
            </ol>
          );
        }

        // Bold text and links
        let processedBlock = block;
        // Bold
        processedBlock = processedBlock.replace(/\*\*([^*]+)\*\*/g, '<strong class="text-gray-900 dark:text-white">$1</strong>');
        // Links
        processedBlock = processedBlock.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" class="text-indigo-600 hover:text-indigo-700 dark:text-indigo-400">$1</a>');

        // Regular paragraphs
        return (
          <p
            key={index}
            className="my-4 text-gray-600 dark:text-gray-300"
            dangerouslySetInnerHTML={{ __html: processedBlock }}
          />
        );
      });
  };

  return (
    <>
      <LandingNavbar />

      {/* Article Header */}
      <Section className="relative overflow-hidden py-16 md:py-24">
        <div className="absolute inset-0 -z-10 bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 dark:from-indigo-950/20 dark:via-purple-950/20 dark:to-pink-950/20" />

        <div className="mx-auto max-w-3xl">
          <Link
            href="/blog"
            className="mb-6 inline-flex items-center gap-2 text-sm font-medium text-indigo-600 transition-colors hover:text-indigo-700 dark:text-indigo-400 dark:hover:text-indigo-300"
          >
            <ArrowLeft className="size-4" />
            Back to Blog
          </Link>

          <div className="mb-4 flex flex-wrap items-center gap-3">
            <span className={`${badgeVariants({ variant: 'default' })} bg-indigo-600`}>
              {post.category}
            </span>
            <span className="flex items-center gap-1 text-sm text-gray-500 dark:text-gray-400">
              <Calendar className="size-4" />
              {new Date(post.date).toLocaleDateString('en-US', {
                month: 'long',
                day: 'numeric',
                year: 'numeric',
              })}
            </span>
            <span className="flex items-center gap-1 text-sm text-gray-500 dark:text-gray-400">
              <Clock className="size-4" />
              {post.readTime}
            </span>
          </div>

          <h1 className="mb-6 text-4xl font-bold tracking-tight text-gray-900 md:text-5xl dark:text-white">
            {post.title}
          </h1>

          <p className="text-xl text-gray-600 dark:text-gray-300">
            {post.excerpt}
          </p>
        </div>
      </Section>

      {/* Article Content */}
      <Section className="border-t border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-900">
        <article className="prose prose-lg prose-gray dark:prose-invert mx-auto max-w-3xl">
          {renderContent(post.content)}
        </article>
      </Section>

      {/* Share & CTA */}
      <Section className="border-t border-gray-200 bg-gradient-to-br from-gray-50 to-white dark:border-gray-700 dark:from-gray-900 dark:to-gray-800">
        <div className="mx-auto max-w-3xl">
          {/* Share */}
          <div className="mb-12 flex items-center justify-between border-b border-gray-200 pb-8 dark:border-gray-700">
            <div>
              <p className="text-sm font-medium text-gray-500 dark:text-gray-400">
                Share this article
              </p>
            </div>
            <div className="flex gap-3">
              <a
                href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(post.title)}&url=${encodeURIComponent(`https://crawlready.com/blog/${props.params.slug}`)}&via=medartus`}
                target="_blank"
                rel="noopener noreferrer"
                className={`${buttonVariants({ variant: 'outline', size: 'sm' })} gap-2`}
              >
                <Share2 className="size-4" />
                Tweet
              </a>
            </div>
          </div>

          {/* CTA */}
          <div className="rounded-2xl border-2 border-indigo-200 bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 p-8 text-center dark:border-indigo-800 dark:from-indigo-950/30 dark:via-purple-950/30 dark:to-pink-950/30">
            <h3 className="mb-4 text-2xl font-bold text-gray-900 dark:text-white">
              Ready to Make Your Site Visible to AI?
            </h3>
            <p className="mb-6 text-gray-600 dark:text-gray-300">
              Join CrawlReady&apos;s early access and get 50% off forever.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Link
                href="/crawler-checker"
                className={`${buttonVariants({ variant: 'outline' })} gap-2`}
              >
                Free Crawler Checker
              </Link>
              <Link
                href="/#early-access"
                className={`${buttonVariants()} gap-2`}
              >
                Join Early Access
                <ArrowRight className="size-4" />
              </Link>
            </div>
          </div>
        </div>
      </Section>

      <LandingFooter />
    </>
  );
};

export default BlogPostPage;
